/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'activityType' : { 'like' : null } |
    { 'comment' : null },
  'commentId' : [] | [string],
  'timestamp' : bigint,
  'activityActor' : Principal,
  'postOwner' : Principal,
  'postId' : string,
}
export interface Comment {
  'id' : string,
  'text' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'postId' : string,
}
export type ExternalBlob = Uint8Array;
export interface Post {
  'id' : string,
  'author' : Principal,
  'likes' : Array<Principal>,
  'timestamp' : bigint,
  'caption' : string,
  'commentCount' : [] | [bigint],
  'image' : ExternalBlob,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followers' : Array<Principal>,
  'following' : Array<Principal>,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addComment' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[ExternalBlob, string], string>,
  'deletePost' : ActorMethod<[string], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getFeed' : ActorMethod<[], Array<Post>>,
  'getGlobalStats' : ActorMethod<
    [],
    {
      'totalActivities' : bigint,
      'totalLikes' : bigint,
      'totalUsers' : bigint,
      'totalPosts' : bigint,
      'totalComments' : bigint,
    }
  >,
  'getInbox' : ActorMethod<[], Array<Activity>>,
  'getMultipleUsersPosts' : ActorMethod<[Array<Principal>], Array<Post>>,
  'getPostLikes' : ActorMethod<[string], bigint>,
  'getRecentProfilePictures' : ActorMethod<[bigint], Array<ExternalBlob>>,
  'getTotalLikesForUser' : ActorMethod<[Principal], bigint>,
  'getUserFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getUserFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getUserPosts' : ActorMethod<[Principal], Array<Post>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeComment' : ActorMethod<[string], undefined>,
  'likePost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
  'unlikeComment' : ActorMethod<[string], undefined>,
  'unlikePost' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];